// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_QeIMow-83We37iUdE1WdywSsaLKJpwE',
    appId: '1:94796923701:web:4be61d6f9c274e9ea0027c',
    messagingSenderId: '94796923701',
    projectId: 'recordify-e4c57',
    authDomain: 'recordify-e4c57.firebaseapp.com',
    storageBucket: 'recordify-e4c57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0j4wvY8yA_Ab7xSY9oA7p4Kl1H_qYzQQ',
    appId: '1:94796923701:android:e6936ca29298787ba0027c',
    messagingSenderId: '94796923701',
    projectId: 'recordify-e4c57',
    storageBucket: 'recordify-e4c57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBww3DVt8v--zMU6qGo36MW8DiL8EYgFXs',
    appId: '1:94796923701:ios:acc8847df8015642a0027c',
    messagingSenderId: '94796923701',
    projectId: 'recordify-e4c57',
    storageBucket: 'recordify-e4c57.appspot.com',
    iosBundleId: 'com.example.recordify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBww3DVt8v--zMU6qGo36MW8DiL8EYgFXs',
    appId: '1:94796923701:ios:b87d20610a4ecea4a0027c',
    messagingSenderId: '94796923701',
    projectId: 'recordify-e4c57',
    storageBucket: 'recordify-e4c57.appspot.com',
    iosBundleId: 'com.example.recordify.RunnerTests',
  );
}
